apiVersion: v1
kind: Service
metadata:
  name: docker-spring-boot-service
spec:
  type: ClusterIP
  selector:
    app: docker-spring-boot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085